name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev-ajay

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Adjust to your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        mv build/* .
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages

